[package]
name = "wellforge-hydraulics-fixtures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uuid.workspace = true
wellforge-hydraulics-contract = { path = "../wellforge-hydraulics-contract", version = "0.1.0" }
wellforge-witsml = { path = "../wellforge-witsml", version = "0.1.0" }

[lints]
workspace = true
